## 1- what is minmax scaling, and how is it used for datapreprocessing ? Provide an example to illustrate its application.

### Ans:- There is another way of data scaling, where the minimum of feature is made equal to zero and the maximum of feature equal to one. MinMax Scaler shrinks the data within the given range, usually of 0 to 1

In [3]:
from sklearn.preprocessing import MinMaxScaler
data = [[11, 2], [3, 7], [0, 10], [11, 8]]
scaler = MinMaxScaler()
model=scaler.fit_transform(data)
print(model)


[[1.         0.        ]
 [0.27272727 0.625     ]
 [0.         1.        ]
 [1.         0.75      ]]


## 2-what is unit vector technique in feature engineering and how is it differs from minmax scaler ? provide an example.

### ans:- Unit Vector TechniqueAlso known as normalization, this technique scales the values of a feature to have a unit norm (typically 1). This is done by dividing each feature value by the Euclidean norm (or L2 norm) of the feature vector.This technique is useful when you want to ensure that the data points lie on a unit hypersphere, which can be beneficial for certain algorithms like k-means clustering1.

### Difference :- Unit vector technique normalizes data to have a unit norm, while min-max scaling adjusts data to fit within a specific range.
### Application: Unit vector technique is often used in clustering algorithms, whereas min-max scaling is commonly used in algorithms sensitive to feature scales, like neural networks and distance-based algorithms.
### Formula: Unit vector technique uses the Euclidean norm, while min-max scaling uses the minimum and maximum values of the feature.

In [6]:
## example
from sklearn.preprocessing import normalize
data = [[11, 2], [3, 7], [0, 10], [11, 8]]

In [8]:
df=normalize(data)

In [9]:
print(df)

[[0.98386991 0.17888544]
 [0.3939193  0.91914503]
 [0.         1.        ]
 [0.80873608 0.5881717 ]]


## 3- what is PCA, and how is it used for dimentionality reduction? Provide an example to illustrate its application.
### ans:- Principal Component Analysis (PCA) is an unsupervised learning algorithm technique used to examine the interrelations among a set of variables. It is also known as a general factor analysis where regression determines a line of best fit. 

## 5-you are working on a project to build a recommendation system for a food delivery service . the database contains features such as price , rating, and delivery time. explain how would you use min max scaling for preprocessing data

###  Min-max scaling transforms features to a specified range, typically between 0 and 1. This ensures that all features contribute equally to the model, improving its performance.
### steps 1-Identify the Features: Determine which features need scaling. In your case, these are price, rating, and delivery time.
### step-2Calculate Minimum and Maximum Values: For each feature, find the minimum and maximum values in the dataset.
### step-3Apply the Scaling Formula: Use the formula to scale each feature value to the range [0, 1].

In [16]:
import numpy as np
import pandas as pd

In [38]:
np.random.randint(100,400,size=30)#low, high=None, size=None, dtype=int

array([290, 226, 303, 335, 207, 252, 152, 330, 167, 229, 365, 177, 353,
       186, 274, 162, 190, 312, 233, 170, 323, 143, 336, 283, 135, 375,
       184, 353, 303, 331])

In [42]:
np.random.randint(1,6,size=30)

array([1, 2, 3, 1, 2, 3, 4, 5, 5, 4, 5, 3, 3, 1, 4, 5, 3, 2, 3, 1, 4, 2,
       1, 2, 3, 3, 2, 5, 5, 4])

In [43]:
np.random.randint(20,40,size=30)

array([23, 35, 31, 37, 29, 24, 35, 30, 34, 38, 32, 29, 37, 24, 38, 23, 28,
       26, 29, 39, 39, 31, 31, 26, 21, 23, 36, 27, 23, 37])

In [58]:
price=pd.DataFrame(np.random.randint(100,400,size=30),columns=['price'])

In [59]:
ratings=pd.DataFrame(np.random.randint(1,6,size=30),columns=['ratings'])

In [60]:
delivery_time=pd.DataFrame(np.random.randint(20,40,size=30),columns=['delivery_time'])

In [62]:
df=pd.concat([price,ratings,delivery_time],axis=1)

In [63]:
df.head()

price  ratings  delivery_time
0    214        3             27
1    382        1             23
2    335        2             23
3    150        2             37
4    158        2             24

In [64]:
from sklearn.preprocessing import MinMaxScaler

In [65]:
scaler=MinMaxScaler()

In [67]:
scaled_data=scaler.fit_transform(df)

In [69]:
pd.DataFrame(scaled_data,columns=['price','ratings','delivery_time'])

price  ratings  delivery_time
0   0.372881     0.50       0.368421
1   0.942373     0.00       0.157895
2   0.783051     0.25       0.157895
3   0.155932     0.25       0.894737
4   0.183051     0.25       0.210526
5   0.518644     1.00       0.842105
6   0.538983     0.75       0.947368
7   0.898305     0.75       0.421053
8   0.444068     0.25       0.368421
9   0.450847     0.25       0.578947
10  1.000000     0.50       0.368421
11  0.000000     0.50       0.578947
12  0.755932     0.50       0.000000
13  0.240678     0.75       0.842105
14  0.176271     0.75       0.210526
15  0.783051     0.25       0.842105
16  0.155932     1.00       0.736842
17  0.589831     0.00       0.631579
18  0.511864     0.75       0.263158
19  0.823729     0.50       0.315789
20  0.766102     0.75       0.947368
21  0.267797     0.50       0.631579
22  0.318644     0.00       0.947368
23  0.179661     1.00       0.263158
24  0.057627     0.75       0.842105
25  0.088136     0.25       0.052632
26  0.057627     0.75       0.736842
27  0.576271     0.75       1.000000
28  0.376271     0.50       0.157895
29  0.949153     0.25       0.842105

## 7 for a dataset containing [1,510,15,20], perform min max scaling to transform the values to a range of -1 to 1

In [70]:
from sklearn.preprocessing import MinMaxScaler

In [71]:
scaler=MinMaxScaler()

In [75]:
data=[1,5,10,15,20]

In [81]:
df=pd.DataFrame(data)
df

0
0   1
1   5
2  10
3  15
4  20

In [82]:
scaler.fit(df)

MinMaxScaler()

In [83]:
scaler.transform(df)

array([[0.        ],
       [0.21052632],
       [0.47368421],
       [0.73684211],
       [1.        ]])